import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme'
import "./globals.css";

export const metadata: Metadata = {
  title: "Pantry Tracker",
  description: "A simple web app to track items in your pantry",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        {/* The AppRouterCacheProvider component is responsible for collecting the CSS generated by MUI 
        System on the server, as Next.js is streaming chunks of the .html page to the client. */}
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {children}

          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
